// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYS7dRZwMPudYX4p1hjKiNtGgdaTHRtRs',
    appId: '1:3995044910:web:b5d0f0d23117cb42f123bf',
    messagingSenderId: '3995044910',
    projectId: 'flutter-firebase-bb872',
    authDomain: 'flutter-firebase-bb872.firebaseapp.com',
    storageBucket: 'flutter-firebase-bb872.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-X66igMMvzEHcab9--FfvyEfNIDZ1v1s',
    appId: '1:3995044910:android:c3d2fa6e7873abd3f123bf',
    messagingSenderId: '3995044910',
    projectId: 'flutter-firebase-bb872',
    storageBucket: 'flutter-firebase-bb872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClWjHfLYEthB46xQq-s512ZDOKrTThIX0',
    appId: '1:3995044910:ios:e7e1874ef5b558d4f123bf',
    messagingSenderId: '3995044910',
    projectId: 'flutter-firebase-bb872',
    storageBucket: 'flutter-firebase-bb872.appspot.com',
    iosBundleId: 'com.example.psBarber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClWjHfLYEthB46xQq-s512ZDOKrTThIX0',
    appId: '1:3995044910:ios:21e82c00a1fa0c3ef123bf',
    messagingSenderId: '3995044910',
    projectId: 'flutter-firebase-bb872',
    storageBucket: 'flutter-firebase-bb872.appspot.com',
    iosBundleId: 'com.example.psBarber.RunnerTests',
  );
}
